version: "3.8"
services:
  postgres:
    labels:
      com.knoldus.app: "postgres"
      com.knoldus.project: "knoldus leaderboard"
    image: postgres:9.6
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    user: root
    privileged: true
    tty: false
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-changeme}
      - POSTGRES_DB=${PG_DATABASE:-leaderboard}
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: postgres
networks:
  backend:
    name: backend