name: Leaderboard

on:
  push:
    branches:
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Compile App
      working-directory: app
      run: sbt compile
    - name: Compile script-to-fetch-all-blogs
      working-directory: script-to-fetch-all-blogs
      run: sbt compile 
    
    - name: Cache .ivy
      uses: actions/cache@v2
      env:
        cache-name: sbt-library-dependencies
      with:
        path: ~/.ivy2
  
