name: Labeling new issue
on:
  issues:
    types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          labels-synonyms: '{"gssoc2021":["GSSOC","GSSOC21","gssoc","Gssoc","GSSoC","gssoc21","gssoc2021","GSSOC2021"]}'