name: Leaderboard Package

on:
  push:
    branches:
      - develop

env:
  ORG: knoldus Inc
  AUTHOR: Shubham Girdhar (girdharshubham)

jobs:
  leaderboard_package:
    env:
      MODULE_NAME: leaderboard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Package
      working-directory: app
      run: |
        sbt docker:publishLocal

    - name: Publish to Github Packages
      run: |
        echo ${{ secrets.TOKEN }} | docker login docker.pkg.github.com -u girdharshubham --password-stdin
        docker tag knoldus_leaderboard:0.1 docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard:0.1
        docker push docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard:0.1
