name: Leaderboard Deploy

on:
  push:
    branches:
      - master 

env:
  ORG: knoldus Inc
  AUTHOR: Shubham Girdhar (girdharshubham)

jobs:
  leaderboard_package:
    env:
      MODULE_NAME: leaderboard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: SSH Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker ps
          docker images
          docker volume ls
