name: Leaderboard Package

on:
  push:
    branches:
      - develop

env:
  ORG: knoldus Inc
  AUTHOR: Shubham Girdhar (girdharshubham)
  PACKAGE_LIST: ""

jobs:
  leaderboard_package:
    env:
      MODULE_NAME: leaderboard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    
    - name: Gather packages to delete
      run: |
        export INPUT_TOKEN=${{ secrets.TOKEN }}
        PACKAGES=$(deploy/list_packages.sh)
        echo '::set-env name=PACKAGE_LIST::$PACKAGES'

    - name: Echo Packages to be deleted
      run: |
        echo $PACKAGE_LIST

    - name: Package
      working-directory: app
      run: |
        sbt docker:publishLocal

    - uses: actions/delete-package-versions@v1
      with:
        package-name: 'knoldus_leaderboard'
        num-old-versions-to-delete: 1

    - name: Publish to Github Packages
      run: |
        echo "==========Docker Login=========="
        echo ${{ secrets.TOKEN }} | docker login docker.pkg.github.com -u girdharshubham --password-stdin

        echo "==========Tagging and pushing with commit=========="
        COMMIT_ID=$(git rev-parse HEAD | cut -b 1-7)
        docker tag knoldus_leaderboard:0.1 docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard:${COMMIT_ID}
        docker push docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard:${COMMIT_ID}

        echo "==========Tagging and publishing latest=========="
        docker tag docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard:${COMMIT_ID} docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard:latest
        docker push docker.pkg.github.com/knoldus/leaderboard/knoldus_leaderboard:latest

    - name: General cleanup
      run: |
        echo "==========Docker logout=========="
        sbt docker:clean
        docker logout docker.pkg.github.com
